### PR TITLE
V3 Release

### PR DESCRIPTION
**Pull request by gjtorikian**
Mostly, this will modernize the gem by dropping old Ruby and Rails implementations. I'm also planning to user kwargs across the filters and methods.

If you're reading this and looking forward to adding a new breaking change, please open an issue to discuss.

Merged PRs for a future changelog:

* https://github.com/gjtorikian/html-pipeline/pull/346 (drop unnecessary ActiveSupport usage, drop Ruby support < 2.5)
* #349
  * Set up kwargs for `context` and `result`
  * Remove deprecated `whitelist` naming
  * Drop CamoFilter, EmailReplyFilter, TextileFilter as they are either GitHub specific or just plain outdated
* https://github.com/gjtorikian/html-pipeline/pull/351
   * Support for multiple dependencies 
* https://github.com/gjtorikian/html-pipeline/pull/360
* Migrate to Selma https://github.com/gjtorikian/html-pipeline/pull/368

### CODE REVIEW

**Comment by digitalmoksha** [comment]
@gjtorikian are you still thinking of moving forward with this branch?  As we're going to be moving to Ruby 3, I'd be interested in seeing a release with the migration to GitHub actions and Ruby 3.1 in the testing matrix, on the current code base. I wonder if you've thought about splitting that out.

**Comment by gjtorikian** [comment]
Yes, I am! Within the next month or so, for sure. I’ve had quite a few irons in the fire but this is still a priority for me.

**Comment by gjtorikian** [comment]
@digitalmoksha Just popping in to say I haven't forgotten about this. Sorry. I expect to release a version at the end of November / early December, as I am rewriting the backend in Rust, for performance reasons.

**Comment by digitalmoksha** [comment]
@gjtorikian 

> Just popping in to say I haven't forgotten about this

Oh no worries! And I spaced on replying to this.

> as I am rewriting the backend in Rust, for performance reasons.

Are you saying you're rewriting _this_ repo in Rust, and dropping Ruby? I know `commonmarker` is going to be using Rust backend, but this gem as well?

> Drop CamoFilter

Just noticed this above. Just as an fyi, we do actually use the `CamoFilter`, https://gitlab.com/gitlab-org/gitlab/blob/master/lib/banzai/filter/asset_proxy_filter.rb.  If that does get removed, I guess we'll inline it.

**Comment by gjtorikian** [comment]
> Are you saying you're rewriting this repo in Rust, and dropping Ruby? I know commonmarker is going to be using Rust backend, but this gem as well?

Yes, see #368 and the underlying repo for more info.

> Just noticed this above. Just as an fyi, we do actually use the `CamoFilter`, https://gitlab.com/gitlab-org/gitlab/blob/master/lib/banzai/filter/asset_proxy_filter.rb. If that does get removed, I guess we'll inline it.

Can you upstream this to here? `AssetProxyFilter` looks much nicer.

**Comment by digitalmoksha** [comment]
> Can you upstream this to here? `AssetProxyFilter` looks much nicer.

Yeah you bet!

**Comment by gjtorikian** [comment]
> > Can you upstream this to here? `AssetProxyFilter` looks much nicer.
> 
> Yeah you bet!

Hey, any interest in upstreaming?

**Comment by digitalmoksha** [comment]
Yeah of course, sorry I spaced on this.  Let me spin something up...

**Comment by digitalmoksha** [comment]
@gjtorikian I'm curious, have you considered creating a Rust version of `html-pipeline`? I'm thinking about moving some of our filters into a Rust based pipeline for speed 🤔

**Comment by gjtorikian** [comment]
I haven't thought about it—but walk me through which part you would want/expect to Rustify ? All I do these days is wrap Rust in Ruby. 😆 

V3 moved the bulk of the HTML selection-manipulation logic to using [selma](https://github.com/gjtorikian/selma), which uses [lol-html](https://github.com/cloudflare/lol-html) under the hood. html-pipeline is now just a dumb interface which takes an array of Ruby classes and iterates over their selectors; but the real manipulation work is done in Rust, and the Ruby class just acts as a sort of sugar on top. If anything, I'd like to move towards turning this into an `async` library (which is partly why I haven't solidified v3 yet--haven't had time to explore what this would entail).

**Comment by digitalmoksha** [comment]
I think it would be basically the same as what you have now, just in Rust - given a vector of filters, run through them calling their transformation function, passing results from one to the other.

Still coming up to speed on Rust's object oriented features, but it seems like using traits might give you the ability to not only gain default functionality of say a `TextFilter`, but allow you to override that functionality as well.

So if we have our own Rust crate which we can move some of our current Ruby filters/pipeline into, then I think we would see some performance win.

Haven't yet attempted to migrate to V3 of `html-pipeline`, so maybe that would be enough of a win.  But I'm still considering having some type of pipeline ability in our Rust crate.

So I thought you might have something in the works ;-)

**Pull request merged**
